Домашка 2.7. 10 задач. 1 игра.
DKTNS/2-nd_course_hw pull request #7
Opened 2023-11-02 15:33 UTC by DKTNS

2023-11-03 15:09 UTC, Mielilon requested changes

2023-11-03 15:09 UTC, Mielilon commented on hw-2.7/hw-2.7.js
> +function randNumb(min, max) {
Функция не учитывает аргументы `min` и `max`, их нужно применить в формуле для получения случайного числа в заданном промежутке.

2023-11-03 15:09 UTC, Mielilon commented on hw-2.7/hw-2.7.js
> +console.log(currentDate);
Последний `console.log(currentDate);` должен быть `console.log(futureDate(todayDate()));`, чтобы корректно вызвать функции и вывести будущую дату.

2023-11-03 15:09 UTC, Mielilon commented on hw-2.7/hw-2.7.js
> +console.log(formatDate(d));
Переменная `d` не определена в текущей области видимости. Необходимо передать объект `Date` при вызове функции `formatDate`, например, `new Date()`.

2023-11-03 15:09 UTC, Mielilon commented on App/game_2.js
> +    const arrFruit = ['Яблоко', 'Груша', 'Дыня', 'Виноград', 'Персик', 'Апельсин', 'Мандарин'];
Нужно заменить на `let`, чтобы игра запускалась без ошибок. Сейчас в консоли можем увидеть следующее:
<img width="485" alt="image" src="https://github.com/DKTNS/2-nd_course_hw/assets/65778664/75c6996c-5e3c-4007-90e2-7258f6bdf583">

Она говорит о том, что в коде происходит ошибка изменить значение константы.

2023-11-04 07:42 UTC, DKTNS commented on hw-2.7/hw-2.7.js
> +function randNumb(min, max) {
Task 5 - исправлено

2023-11-04 08:26 UTC, DKTNS commented on hw-2.7/hw-2.7.js
> +console.log(currentDate);
Task 9 - исправлено

2023-11-05 11:37 UTC, merged